# coding: utf-8

"""
    TemplateFox API

    Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

    The version of the OpenAPI document: 1.10.0
    Contact: support@templatefox.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from templatefox.models.merge_pdf_request import MergePdfRequest

class TestMergePdfRequest(unittest.TestCase):
    """MergePdfRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MergePdfRequest:
        """Test MergePdfRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MergePdfRequest`
        """
        model = MergePdfRequest()
        if include_optional:
            return MergePdfRequest(
                export_type = 'url',
                expiration = 60.0,
                filename = '2',
                pdfs = [
                    templatefox.models.pdf_input.PdfInput(
                        pdf_url = '', 
                        pdf_base64 = '', )
                    ]
            )
        else:
            return MergePdfRequest(
                pdfs = [
                    templatefox.models.pdf_input.PdfInput(
                        pdf_url = '', 
                        pdf_base64 = '', )
                    ],
        )
        """

    def testMergePdfRequest(self):
        """Test MergePdfRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
