# coding: utf-8

"""
    TemplateFox API

    Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

    The version of the OpenAPI document: 1.13.0
    Contact: support@templatefox.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from templatefox.models.modification import Modification

class TestModification(unittest.TestCase):
    """Modification unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Modification:
        """Test Modification
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Modification`
        """
        model = Modification()
        if include_optional:
            return Modification(
                name = '0',
                text = '',
                image_url = 'https:/',
                color = '',
                background = '',
                hidden = True
            )
        else:
            return Modification(
                name = '0',
        )
        """

    def testModification(self):
        """Test Modification"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
