# coding: utf-8

"""
    TemplateFox API

    Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

    The version of the OpenAPI document: 1.3.0
    Contact: support@pdftemplateapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from templatefox.models.templates_list_response import TemplatesListResponse

class TestTemplatesListResponse(unittest.TestCase):
    """TemplatesListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TemplatesListResponse:
        """Test TemplatesListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TemplatesListResponse`
        """
        model = TemplatesListResponse()
        if include_optional:
            return TemplatesListResponse(
                templates = [
                    templatefox.models.template_list_item.TemplateListItem(
                        id = '', 
                        name = '', 
                        created_at = '', 
                        updated_at = '', )
                    ]
            )
        else:
            return TemplatesListResponse(
                templates = [
                    templatefox.models.template_list_item.TemplateListItem(
                        id = '', 
                        name = '', 
                        created_at = '', 
                        updated_at = '', )
                    ],
        )
        """

    def testTemplatesListResponse(self):
        """Test TemplatesListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
