# coding: utf-8

"""
    TemplateFox API

    Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

    The version of the OpenAPI document: 1.4.0
    Contact: support@pdftemplateapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from templatefox.models.s3_success_response import S3SuccessResponse

class TestS3SuccessResponse(unittest.TestCase):
    """S3SuccessResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> S3SuccessResponse:
        """Test S3SuccessResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `S3SuccessResponse`
        """
        model = S3SuccessResponse()
        if include_optional:
            return S3SuccessResponse(
                success = True
            )
        else:
            return S3SuccessResponse(
                success = True,
        )
        """

    def testS3SuccessResponse(self):
        """Test S3SuccessResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
