# coding: utf-8

"""
    TemplateFox API

    Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

    The version of the OpenAPI document: 1.10.0
    Contact: support@templatefox.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from templatefox.models.app_routers_v1_pdf_tools_export_type import AppRoutersV1PdfToolsExportType

class TestAppRoutersV1PdfToolsExportType(unittest.TestCase):
    """AppRoutersV1PdfToolsExportType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAppRoutersV1PdfToolsExportType(self):
        """Test AppRoutersV1PdfToolsExportType"""
        # inst = AppRoutersV1PdfToolsExportType()

if __name__ == '__main__':
    unittest.main()
