# coding: utf-8

"""
    TemplateFox API

    Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

    The version of the OpenAPI document: 1.6.1
    Contact: support@pdftemplateapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from templatefox.models.create_pdf_request import CreatePdfRequest

class TestCreatePdfRequest(unittest.TestCase):
    """CreatePdfRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreatePdfRequest:
        """Test CreatePdfRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreatePdfRequest`
        """
        model = CreatePdfRequest()
        if include_optional:
            return CreatePdfRequest(
                template_id = '01234567891011',
                data = { },
                export_type = 'url',
                expiration = 60.0,
                filename = '2',
                store_s3 = True,
                s3_filepath = '/',
                s3_bucket = 'wwat4ikwowtta-2mh1lcafqw2zhes0012'
            )
        else:
            return CreatePdfRequest(
                template_id = '01234567891011',
                data = { },
        )
        """

    def testCreatePdfRequest(self):
        """Test CreatePdfRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
