# coding: utf-8

"""
    TemplateFox API

    Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

    The version of the OpenAPI document: 1.10.0
    Contact: support@templatefox.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from templatefox.api.templates_api import TemplatesApi


class TestTemplatesApi(unittest.TestCase):
    """TemplatesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TemplatesApi()

    def tearDown(self) -> None:
        pass

    def test_create_template_version(self) -> None:
        """Test case for create_template_version

        Create a version snapshot
        """
        pass

    def test_delete_template_version(self) -> None:
        """Test case for delete_template_version

        Delete a version
        """
        pass

    def test_get_template_fields(self) -> None:
        """Test case for get_template_fields

        Get template fields
        """
        pass

    def test_list_template_versions(self) -> None:
        """Test case for list_template_versions

        List template versions
        """
        pass

    def test_list_templates(self) -> None:
        """Test case for list_templates

        List templates
        """
        pass

    def test_update_template_version(self) -> None:
        """Test case for update_template_version

        Update a version
        """
        pass


if __name__ == '__main__':
    unittest.main()
