# coding: utf-8

"""
    TemplateFox API

    Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

    The version of the OpenAPI document: 1.6.1
    Contact: support@pdftemplateapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from templatefox.models.create_async_pdf_request import CreateAsyncPdfRequest

class TestCreateAsyncPdfRequest(unittest.TestCase):
    """CreateAsyncPdfRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateAsyncPdfRequest:
        """Test CreateAsyncPdfRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateAsyncPdfRequest`
        """
        model = CreateAsyncPdfRequest()
        if include_optional:
            return CreateAsyncPdfRequest(
                template_id = '01234567891011',
                data = { },
                export_type = 'url',
                expiration = 60.0,
                filename = '2',
                store_s3 = True,
                s3_filepath = '/',
                s3_bucket = 'wwat4ikwowtta-2mh1lcafqw2zhes0012',
                webhook_url = '0',
                webhook_secret = '0123456789101112131415'
            )
        else:
            return CreateAsyncPdfRequest(
                template_id = '01234567891011',
                data = { },
        )
        """

    def testCreateAsyncPdfRequest(self):
        """Test CreateAsyncPdfRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
