# coding: utf-8

"""
    TemplateFox API

    Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

    The version of the OpenAPI document: 1.6.1
    Contact: support@pdftemplateapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from templatefox.models.job_status_response import JobStatusResponse

class TestJobStatusResponse(unittest.TestCase):
    """JobStatusResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JobStatusResponse:
        """Test JobStatusResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JobStatusResponse`
        """
        model = JobStatusResponse()
        if include_optional:
            return JobStatusResponse(
                id = '',
                status = 'pending',
                template_id = '',
                export_type = '',
                filename = '',
                store_s3 = True,
                created_at = '',
                updated_at = '',
                completed_at = '',
                result_url = '',
                result_filename = '',
                result_expires_at = '',
                result_s3_bucket = '',
                result_s3_key = '',
                error_message = '',
                error_code = ''
            )
        else:
            return JobStatusResponse(
                id = '',
                status = 'pending',
                template_id = '',
                export_type = '',
                store_s3 = True,
                created_at = '',
                updated_at = '',
        )
        """

    def testJobStatusResponse(self):
        """Test JobStatusResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
