# coding: utf-8

"""
    TemplateFox API

    Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

    The version of the OpenAPI document: 1.13.0
    Contact: support@templatefox.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from templatefox.models.create_image_request import CreateImageRequest

class TestCreateImageRequest(unittest.TestCase):
    """CreateImageRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateImageRequest:
        """Test CreateImageRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateImageRequest`
        """
        model = CreateImageRequest()
        if include_optional:
            return CreateImageRequest(
                template_id = '01234567891011',
                modifications = [
                    templatefox.models.modification.Modification(
                        name = '0', 
                        text = '', 
                        image_url = 'https:/', 
                        color = '', 
                        background = '', 
                        hidden = True, )
                    ],
                data = { },
                format = 'png',
                width = 100.0,
                quality = 1.0,
                export_type = 'url',
                expiration = 60.0,
                filename = '2',
                store_s3 = True,
                s3_filepath = '/',
                s3_bucket = 'wwat4ikwowtta-2mh1lcafqw2zhes0012',
                version = ''
            )
        else:
            return CreateImageRequest(
                template_id = '01234567891011',
        )
        """

    def testCreateImageRequest(self):
        """Test CreateImageRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
