# coding: utf-8

"""
    TemplateFox API

    Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

    The version of the OpenAPI document: 1.13.0
    Contact: support@templatefox.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from templatefox.models.create_agent_template_request_preset import CreateAgentTemplateRequestPreset

class TestCreateAgentTemplateRequestPreset(unittest.TestCase):
    """CreateAgentTemplateRequestPreset unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateAgentTemplateRequestPreset(self):
        """Test CreateAgentTemplateRequestPreset"""
        # inst = CreateAgentTemplateRequestPreset()

if __name__ == '__main__':
    unittest.main()
