# coding: utf-8

"""
    TemplateFox API

    Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

    The version of the OpenAPI document: 1.3.0
    Contact: support@pdftemplateapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from templatefox.api.pdf_api import PDFApi


class TestPDFApi(unittest.TestCase):
    """PDFApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PDFApi()

    def tearDown(self) -> None:
        pass

    def test_create_pdf(self) -> None:
        """Test case for create_pdf

        Generate PDF from template
        """
        pass


if __name__ == '__main__':
    unittest.main()
