# coding: utf-8

"""
    TemplateFox API

    Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

    The version of the OpenAPI document: 1.10.0
    Contact: support@templatefox.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from templatefox.models.rotate_pdf_request import RotatePdfRequest

class TestRotatePdfRequest(unittest.TestCase):
    """RotatePdfRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RotatePdfRequest:
        """Test RotatePdfRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RotatePdfRequest`
        """
        model = RotatePdfRequest()
        if include_optional:
            return RotatePdfRequest(
                export_type = 'url',
                expiration = 60.0,
                filename = '2',
                pdf_url = '',
                pdf_base64 = '',
                rotation = 56,
                page_rotations = {
                    'key' : 56
                    }
            )
        else:
            return RotatePdfRequest(
        )
        """

    def testRotatePdfRequest(self):
        """Test RotatePdfRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
