# coding: utf-8

"""
    TemplateFox API

    Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

    The version of the OpenAPI document: 1.13.0
    Contact: support@templatefox.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from templatefox.models.revise_agent_template_request import ReviseAgentTemplateRequest

class TestReviseAgentTemplateRequest(unittest.TestCase):
    """ReviseAgentTemplateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReviseAgentTemplateRequest:
        """Test ReviseAgentTemplateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReviseAgentTemplateRequest`
        """
        model = ReviseAgentTemplateRequest()
        if include_optional:
            return ReviseAgentTemplateRequest(
                feedback = '01234',
                brand = templatefox.models.brand_inputs.BrandInputs(
                    colors = [
                        ''
                        ], 
                    fonts = [
                        ''
                        ], 
                    asset_urls = [
                        '0'
                        ], )
            )
        else:
            return ReviseAgentTemplateRequest(
                feedback = '01234',
        )
        """

    def testReviseAgentTemplateRequest(self):
        """Test ReviseAgentTemplateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
