# coding: utf-8

"""
    TemplateFox API

    Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

    The version of the OpenAPI document: 1.4.0
    Contact: support@pdftemplateapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from templatefox.models.s3_config_response import S3ConfigResponse

class TestS3ConfigResponse(unittest.TestCase):
    """S3ConfigResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> S3ConfigResponse:
        """Test S3ConfigResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `S3ConfigResponse`
        """
        model = S3ConfigResponse()
        if include_optional:
            return S3ConfigResponse(
                configured = True,
                endpoint_url = '',
                access_key_id = '',
                secret_access_key_masked = '',
                bucket_name = '',
                default_prefix = ''
            )
        else:
            return S3ConfigResponse(
                configured = True,
                endpoint_url = '',
                access_key_id = '',
                secret_access_key_masked = '',
                bucket_name = '',
                default_prefix = '',
        )
        """

    def testS3ConfigResponse(self):
        """Test S3ConfigResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
