# coding: utf-8

"""
    TemplateFox API

    Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

    The version of the OpenAPI document: 1.4.0
    Contact: support@pdftemplateapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from templatefox.models.s3_config_request import S3ConfigRequest

class TestS3ConfigRequest(unittest.TestCase):
    """S3ConfigRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> S3ConfigRequest:
        """Test S3ConfigRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `S3ConfigRequest`
        """
        model = S3ConfigRequest()
        if include_optional:
            return S3ConfigRequest(
                endpoint_url = 'https:/0123456789',
                access_key_id = '0123456789101112131415',
                secret_access_key = '0123456789101112131415',
                bucket_name = 'wwat4ikwowtta-2mh1lcafqw2zhes0012',
                default_prefix = '/B98JLe5iL60-aa-.Ctq9d'
            )
        else:
            return S3ConfigRequest(
                endpoint_url = 'https:/0123456789',
                access_key_id = '0123456789101112131415',
                bucket_name = 'wwat4ikwowtta-2mh1lcafqw2zhes0012',
        )
        """

    def testS3ConfigRequest(self):
        """Test S3ConfigRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
