# coding: utf-8

"""
    TemplateFox API

    Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

    The version of the OpenAPI document: 1.13.0
    Contact: support@templatefox.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from templatefox.models.app_routers_v1_pdf_async_job_status import AppRoutersV1PdfAsyncJobStatus

class TestAppRoutersV1PdfAsyncJobStatus(unittest.TestCase):
    """AppRoutersV1PdfAsyncJobStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAppRoutersV1PdfAsyncJobStatus(self):
        """Test AppRoutersV1PdfAsyncJobStatus"""
        # inst = AppRoutersV1PdfAsyncJobStatus()

if __name__ == '__main__':
    unittest.main()
