# coding: utf-8

"""
    TemplateFox API

    Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

    The version of the OpenAPI document: 1.11.0
    Contact: support@templatefox.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from templatefox.models.image_format import ImageFormat

class TestImageFormat(unittest.TestCase):
    """ImageFormat unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testImageFormat(self):
        """Test ImageFormat"""
        # inst = ImageFormat()

if __name__ == '__main__':
    unittest.main()
