# coding: utf-8

"""
    TemplateFox API

    Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

    The version of the OpenAPI document: 1.13.0
    Contact: support@templatefox.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from templatefox.models.app_routers_v1_agent_job_status import AppRoutersV1AgentJobStatus

class TestAppRoutersV1AgentJobStatus(unittest.TestCase):
    """AppRoutersV1AgentJobStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAppRoutersV1AgentJobStatus(self):
        """Test AppRoutersV1AgentJobStatus"""
        # inst = AppRoutersV1AgentJobStatus()

if __name__ == '__main__':
    unittest.main()
