# coding: utf-8

"""
    TemplateFox API

    Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

    The version of the OpenAPI document: 1.9.0
    Contact: support@templatefox.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from templatefox.models.versions_list_response import VersionsListResponse

class TestVersionsListResponse(unittest.TestCase):
    """VersionsListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VersionsListResponse:
        """Test VersionsListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VersionsListResponse`
        """
        model = VersionsListResponse()
        if include_optional:
            return VersionsListResponse(
                versions = [
                    templatefox.models.version_item.VersionItem(
                        version_number = 56, 
                        tag = '', 
                        description = '', 
                        is_default = True, 
                        created_at = '', )
                    ]
            )
        else:
            return VersionsListResponse(
                versions = [
                    templatefox.models.version_item.VersionItem(
                        version_number = 56, 
                        tag = '', 
                        description = '', 
                        is_default = True, 
                        created_at = '', )
                    ],
        )
        """

    def testVersionsListResponse(self):
        """Test VersionsListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
