# coding: utf-8

"""
    TemplateFox API

    Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

    The version of the OpenAPI document: 1.11.0
    Contact: support@templatefox.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from templatefox.models.create_image_response import CreateImageResponse

class TestCreateImageResponse(unittest.TestCase):
    """CreateImageResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateImageResponse:
        """Test CreateImageResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateImageResponse`
        """
        model = CreateImageResponse()
        if include_optional:
            return CreateImageResponse(
                url = '',
                filename = '',
                credits_remaining = 56,
                expires_in = 56,
                warnings = [
                    ''
                    ]
            )
        else:
            return CreateImageResponse(
                url = '',
                filename = '',
                credits_remaining = 56,
                expires_in = 56,
        )
        """

    def testCreateImageResponse(self):
        """Test CreateImageResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
