# coding: utf-8

"""
    TemplateFox API

    Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

    The version of the OpenAPI document: 1.4.0
    Contact: support@pdftemplateapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from templatefox.models.export_type import ExportType

class TestExportType(unittest.TestCase):
    """ExportType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExportType(self):
        """Test ExportType"""
        # inst = ExportType()

if __name__ == '__main__':
    unittest.main()
