# coding: utf-8

"""
    TemplateFox API

    Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

    The version of the OpenAPI document: 1.9.2
    Contact: support@templatefox.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from templatefox.models.update_version_request import UpdateVersionRequest

class TestUpdateVersionRequest(unittest.TestCase):
    """UpdateVersionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateVersionRequest:
        """Test UpdateVersionRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateVersionRequest`
        """
        model = UpdateVersionRequest()
        if include_optional:
            return UpdateVersionRequest(
                tag = 'wwat5ikwowtta-3mh2lcafqw37',
                description = ''
            )
        else:
            return UpdateVersionRequest(
        )
        """

    def testUpdateVersionRequest(self):
        """Test UpdateVersionRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
