# coding: utf-8

"""
    TemplateFox API

    Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

    The version of the OpenAPI document: 1.6.1
    Contact: support@pdftemplateapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from templatefox.api.pdf_async_api import PDFAsyncApi


class TestPDFAsyncApi(unittest.TestCase):
    """PDFAsyncApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PDFAsyncApi()

    def tearDown(self) -> None:
        pass

    def test_create_pdf_async(self) -> None:
        """Test case for create_pdf_async

        Generate PDF asynchronously
        """
        pass

    def test_get_pdf_job(self) -> None:
        """Test case for get_pdf_job

        Get PDF job status
        """
        pass

    def test_list_pdf_jobs(self) -> None:
        """Test case for list_pdf_jobs

        List PDF jobs
        """
        pass


if __name__ == '__main__':
    unittest.main()
