# coding: utf-8

"""
    TemplateFox API

    Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

    The version of the OpenAPI document: 1.13.0
    Contact: support@templatefox.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from templatefox.models.agent_job_status_response import AgentJobStatusResponse

class TestAgentJobStatusResponse(unittest.TestCase):
    """AgentJobStatusResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AgentJobStatusResponse:
        """Test AgentJobStatusResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AgentJobStatusResponse`
        """
        model = AgentJobStatusResponse()
        if include_optional:
            return AgentJobStatusResponse(
                id = '',
                kind = 'create',
                status = 'pending',
                template_id = '',
                preview_url = '',
                preview_expires_at = '',
                notes = '',
                credits_charged = 56,
                error_message = '',
                error_code = '',
                created_at = '',
                updated_at = '',
                completed_at = ''
            )
        else:
            return AgentJobStatusResponse(
                id = '',
                kind = 'create',
                status = 'pending',
                credits_charged = 56,
                created_at = '',
                updated_at = '',
        )
        """

    def testAgentJobStatusResponse(self):
        """Test AgentJobStatusResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
