# coding: utf-8

"""
    TemplateFox API

    Generate PDFs from HTML templates via API. Design once, generate thousands.

    The version of the OpenAPI document: 1.0.0
    Contact: support@pdftemplateapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from templatefox.models.transactions_response import TransactionsResponse

class TestTransactionsResponse(unittest.TestCase):
    """TransactionsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TransactionsResponse:
        """Test TransactionsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransactionsResponse`
        """
        model = TransactionsResponse()
        if include_optional:
            return TransactionsResponse(
                transactions = [
                    templatefox.models.transaction.Transaction(
                        transaction_ref = '', 
                        transaction_type = '', 
                        template_id = '', 
                        exec_tm = 56, 
                        credits = 56, 
                        created_at = '', )
                    ],
                total = 56,
                limit = 56,
                offset = 56
            )
        else:
            return TransactionsResponse(
                transactions = [
                    templatefox.models.transaction.Transaction(
                        transaction_ref = '', 
                        transaction_type = '', 
                        template_id = '', 
                        exec_tm = 56, 
                        credits = 56, 
                        created_at = '', )
                    ],
                total = 56,
                limit = 56,
                offset = 56,
        )
        """

    def testTransactionsResponse(self):
        """Test TransactionsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
