# coding: utf-8

"""
    TemplateFox API

    Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

    The version of the OpenAPI document: 1.3.0
    Contact: support@pdftemplateapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from templatefox.models.template_field import TemplateField

class TestTemplateField(unittest.TestCase):
    """TemplateField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TemplateField:
        """Test TemplateField
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TemplateField`
        """
        model = TemplateField()
        if include_optional:
            return TemplateField(
                key = '',
                label = '',
                type = 'string',
                required = True,
                help_text = '',
                spec = [
                    templatefox.models.template_field_spec.TemplateFieldSpec(
                        name = '', 
                        label = '', 
                        type = 'text', )
                    ]
            )
        else:
            return TemplateField(
                key = '',
                label = '',
        )
        """

    def testTemplateField(self):
        """Test TemplateField"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
