# coding: utf-8

"""
    TemplateFox API

    Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

    The version of the OpenAPI document: 1.13.0
    Contact: support@templatefox.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from templatefox.models.create_agent_template_request import CreateAgentTemplateRequest

class TestCreateAgentTemplateRequest(unittest.TestCase):
    """CreateAgentTemplateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateAgentTemplateRequest:
        """Test CreateAgentTemplateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateAgentTemplateRequest`
        """
        model = CreateAgentTemplateRequest()
        if include_optional:
            return CreateAgentTemplateRequest(
                instructions = '0123456789',
                name = '0',
                preset = 'instagram-square',
                width = 16.0,
                height = 16.0,
                brand = templatefox.models.brand_inputs.BrandInputs(
                    colors = [
                        ''
                        ], 
                    fonts = [
                        ''
                        ], 
                    asset_urls = [
                        '0'
                        ], )
            )
        else:
            return CreateAgentTemplateRequest(
                instructions = '0123456789',
                name = '0',
        )
        """

    def testCreateAgentTemplateRequest(self):
        """Test CreateAgentTemplateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
