# coding: utf-8

"""
    TemplateFox API

    Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

    The version of the OpenAPI document: 1.6.1
    Contact: support@pdftemplateapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from templatefox.models.app_routers_v1_pdf_async_export_type import AppRoutersV1PdfAsyncExportType

class TestAppRoutersV1PdfAsyncExportType(unittest.TestCase):
    """AppRoutersV1PdfAsyncExportType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAppRoutersV1PdfAsyncExportType(self):
        """Test AppRoutersV1PdfAsyncExportType"""
        # inst = AppRoutersV1PdfAsyncExportType()

if __name__ == '__main__':
    unittest.main()
