# coding: utf-8

"""
    TemplateFox API

    Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

    The version of the OpenAPI document: 1.10.0
    Contact: support@templatefox.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from templatefox.api.pdf_tools_api import PDFToolsApi


class TestPDFToolsApi(unittest.TestCase):
    """PDFToolsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PDFToolsApi()

    def tearDown(self) -> None:
        pass

    def test_extract_pdf_pages(self) -> None:
        """Test case for extract_pdf_pages

        Extract pages from a PDF
        """
        pass

    def test_merge_pdf(self) -> None:
        """Test case for merge_pdf

        Merge PDFs
        """
        pass

    def test_rotate_pdf(self) -> None:
        """Test case for rotate_pdf

        Rotate pages of a PDF
        """
        pass


if __name__ == '__main__':
    unittest.main()
