# coding: utf-8

"""
    TemplateFox API

    Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

    The version of the OpenAPI document: 1.6.1
    Contact: support@pdftemplateapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from templatefox.models.app_routers_v1_pdf_export_type import AppRoutersV1PdfExportType

class TestAppRoutersV1PdfExportType(unittest.TestCase):
    """AppRoutersV1PdfExportType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAppRoutersV1PdfExportType(self):
        """Test AppRoutersV1PdfExportType"""
        # inst = AppRoutersV1PdfExportType()

if __name__ == '__main__':
    unittest.main()
