# coding: utf-8

"""
    TemplateFox API

    Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

    The version of the OpenAPI document: 1.6.1
    Contact: support@pdftemplateapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from templatefox.models.create_async_pdf_response import CreateAsyncPdfResponse

class TestCreateAsyncPdfResponse(unittest.TestCase):
    """CreateAsyncPdfResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateAsyncPdfResponse:
        """Test CreateAsyncPdfResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateAsyncPdfResponse`
        """
        model = CreateAsyncPdfResponse()
        if include_optional:
            return CreateAsyncPdfResponse(
                job_id = '',
                status = 'pending',
                credits_remaining = 56
            )
        else:
            return CreateAsyncPdfResponse(
                job_id = '',
                status = 'pending',
                credits_remaining = 56,
        )
        """

    def testCreateAsyncPdfResponse(self):
        """Test CreateAsyncPdfResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
