# coding: utf-8

"""
    TemplateFox API

    Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

    The version of the OpenAPI document: 1.10.0
    Contact: support@templatefox.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from templatefox.models.extract_pdf_pages_request import ExtractPdfPagesRequest

class TestExtractPdfPagesRequest(unittest.TestCase):
    """ExtractPdfPagesRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExtractPdfPagesRequest:
        """Test ExtractPdfPagesRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExtractPdfPagesRequest`
        """
        model = ExtractPdfPagesRequest()
        if include_optional:
            return ExtractPdfPagesRequest(
                export_type = 'url',
                expiration = 60.0,
                filename = '2',
                pdf_url = '',
                pdf_base64 = '',
                pages = ''
            )
        else:
            return ExtractPdfPagesRequest(
                pages = '',
        )
        """

    def testExtractPdfPagesRequest(self):
        """Test ExtractPdfPagesRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
