# coding: utf-8

"""
    TemplateFox API

    Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

    The version of the OpenAPI document: 1.10.0
    Contact: support@templatefox.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from templatefox.models.pdf_tools_response import PdfToolsResponse

class TestPdfToolsResponse(unittest.TestCase):
    """PdfToolsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PdfToolsResponse:
        """Test PdfToolsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PdfToolsResponse`
        """
        model = PdfToolsResponse()
        if include_optional:
            return PdfToolsResponse(
                url = '',
                filename = '',
                credits_remaining = 56,
                expires_in = 56
            )
        else:
            return PdfToolsResponse(
                url = '',
                filename = '',
                credits_remaining = 56,
                expires_in = 56,
        )
        """

    def testPdfToolsResponse(self):
        """Test PdfToolsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
