# coding: utf-8

"""
    TemplateFox API

    Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

    The version of the OpenAPI document: 1.13.0
    Contact: support@templatefox.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from templatefox.models.app_routers_v1_delivery_export_type import AppRoutersV1DeliveryExportType

class TestAppRoutersV1DeliveryExportType(unittest.TestCase):
    """AppRoutersV1DeliveryExportType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAppRoutersV1DeliveryExportType(self):
        """Test AppRoutersV1DeliveryExportType"""
        # inst = AppRoutersV1DeliveryExportType()

if __name__ == '__main__':
    unittest.main()
