# coding: utf-8

"""
    TemplateFox API

    Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

    The version of the OpenAPI document: 1.8.1
    Contact: support@templatefox.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from templatefox.models.pdf_variant import PdfVariant

class TestPdfVariant(unittest.TestCase):
    """PdfVariant unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPdfVariant(self):
        """Test PdfVariant"""
        # inst = PdfVariant()

if __name__ == '__main__':
    unittest.main()
