# coding: utf-8

"""
    TemplateFox API

    Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

    The version of the OpenAPI document: 1.6.1
    Contact: support@pdftemplateapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from templatefox.models.account_info_response import AccountInfoResponse

class TestAccountInfoResponse(unittest.TestCase):
    """AccountInfoResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AccountInfoResponse:
        """Test AccountInfoResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AccountInfoResponse`
        """
        model = AccountInfoResponse()
        if include_optional:
            return AccountInfoResponse(
                credits = 56,
                email = ''
            )
        else:
            return AccountInfoResponse(
                credits = 56,
        )
        """

    def testAccountInfoResponse(self):
        """Test AccountInfoResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
