# coding: utf-8

"""
    TemplateFox API

    Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

    The version of the OpenAPI document: 1.12.0
    Contact: support@templatefox.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from templatefox.models.template_layers_response import TemplateLayersResponse

class TestTemplateLayersResponse(unittest.TestCase):
    """TemplateLayersResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TemplateLayersResponse:
        """Test TemplateLayersResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TemplateLayersResponse`
        """
        model = TemplateLayersResponse()
        if include_optional:
            return TemplateLayersResponse(
                layers = [
                    templatefox.models.template_layer.TemplateLayer(
                        name = '', 
                        tag = '', 
                        type = '', 
                        current_text = '', 
                        modifiable = [
                            ''
                            ], )
                    ],
                warnings = [
                    ''
                    ]
            )
        else:
            return TemplateLayersResponse(
                layers = [
                    templatefox.models.template_layer.TemplateLayer(
                        name = '', 
                        tag = '', 
                        type = '', 
                        current_text = '', 
                        modifiable = [
                            ''
                            ], )
                    ],
        )
        """

    def testTemplateLayersResponse(self):
        """Test TemplateLayersResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
