# coding: utf-8

"""
    TemplateFox API

    Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

    The version of the OpenAPI document: 1.13.0
    Contact: support@templatefox.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from templatefox.models.app_routers_v1_agent_job_status import AppRoutersV1AgentJobStatus
from templatefox.models.kind import Kind
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AgentJobStatusResponse(BaseModel):
    """
    AgentJobStatusResponse
    """ # noqa: E501
    id: StrictStr
    kind: Kind
    status: AppRoutersV1AgentJobStatus
    template_id: Optional[StrictStr] = None
    preview_url: Optional[StrictStr] = None
    preview_expires_at: Optional[StrictStr] = None
    notes: Optional[StrictStr] = None
    credits_charged: StrictInt
    error_message: Optional[StrictStr] = None
    error_code: Optional[StrictStr] = None
    created_at: StrictStr
    updated_at: StrictStr
    completed_at: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["id", "kind", "status", "template_id", "preview_url", "preview_expires_at", "notes", "credits_charged", "error_message", "error_code", "created_at", "updated_at", "completed_at"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AgentJobStatusResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if template_id (nullable) is None
        # and model_fields_set contains the field
        if self.template_id is None and "template_id" in self.model_fields_set:
            _dict['template_id'] = None

        # set to None if preview_url (nullable) is None
        # and model_fields_set contains the field
        if self.preview_url is None and "preview_url" in self.model_fields_set:
            _dict['preview_url'] = None

        # set to None if preview_expires_at (nullable) is None
        # and model_fields_set contains the field
        if self.preview_expires_at is None and "preview_expires_at" in self.model_fields_set:
            _dict['preview_expires_at'] = None

        # set to None if notes (nullable) is None
        # and model_fields_set contains the field
        if self.notes is None and "notes" in self.model_fields_set:
            _dict['notes'] = None

        # set to None if error_message (nullable) is None
        # and model_fields_set contains the field
        if self.error_message is None and "error_message" in self.model_fields_set:
            _dict['error_message'] = None

        # set to None if error_code (nullable) is None
        # and model_fields_set contains the field
        if self.error_code is None and "error_code" in self.model_fields_set:
            _dict['error_code'] = None

        # set to None if completed_at (nullable) is None
        # and model_fields_set contains the field
        if self.completed_at is None and "completed_at" in self.model_fields_set:
            _dict['completed_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AgentJobStatusResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "kind": obj.get("kind"),
            "status": obj.get("status"),
            "template_id": obj.get("template_id"),
            "preview_url": obj.get("preview_url"),
            "preview_expires_at": obj.get("preview_expires_at"),
            "notes": obj.get("notes"),
            "credits_charged": obj.get("credits_charged"),
            "error_message": obj.get("error_message"),
            "error_code": obj.get("error_code"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "completed_at": obj.get("completed_at")
        })
        return _obj


