# coding: utf-8

"""
    TemplateFox API

    Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

    The version of the OpenAPI document: 1.13.0
    Contact: support@templatefox.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class CreateAgentTemplateRequestPreset(str, Enum):
    """
    CreateAgentTemplateRequestPreset
    """

    """
    allowed enum values
    """
    INSTAGRAM_MINUS_SQUARE = 'instagram-square'
    INSTAGRAM_MINUS_STORY = 'instagram-story'
    OG_MINUS_IMAGE = 'og-image'
    TWITTER_MINUS_CARD = 'twitter-card'
    PINTEREST_MINUS_PIN = 'pinterest-pin'
    SQUARE_MINUS_512 = 'square-512'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CreateAgentTemplateRequestPreset from a JSON string"""
        return cls(json.loads(json_str))


