# coding: utf-8

"""
    TemplateFox API

    Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

    The version of the OpenAPI document: 1.4.0
    Contact: support@pdftemplateapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from templatefox.models.export_type import ExportType
from typing import Optional, Set
from typing_extensions import Self

class CreatePdfRequest(BaseModel):
    """
    Request model for PDF generation
    """ # noqa: E501
    template_id: Annotated[str, Field(min_length=12, strict=True, max_length=12)] = Field(description="**Required.** Template short ID (12 characters)")
    data: Dict[str, Any] = Field(description="**Required.** Key-value data to render in the template. Keys must match template variables.")
    export_type: Optional[ExportType] = Field(default=None, description="Export format: `url` uploads to CDN and returns URL, `binary` returns raw PDF bytes")
    expiration: Optional[Annotated[int, Field(le=604800, strict=True, ge=60)]] = Field(default=86400, description="URL expiration in seconds. Min: 60 (1 min), Max: 604800 (7 days). Only applies to `url` export type.")
    filename: Optional[Annotated[str, Field(strict=True, max_length=100)]] = None
    store_s3: Optional[StrictBool] = Field(default=False, description="Upload to your configured S3 bucket instead of CDN")
    s3_filepath: Optional[Annotated[str, Field(strict=True, max_length=500)]] = None
    s3_bucket: Optional[Annotated[str, Field(min_length=3, strict=True, max_length=63)]] = None
    __properties: ClassVar[List[str]] = ["template_id", "data", "export_type", "expiration", "filename", "store_s3", "s3_filepath", "s3_bucket"]

    @field_validator('filename')
    def filename_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[a-zA-Z0-9_\-\.]+$", value):
            raise ValueError(r"must validate the regular expression /^[a-zA-Z0-9_\-\.]+$/")
        return value

    @field_validator('s3_filepath')
    def s3_filepath_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[a-zA-Z0-9_\-\.\/]+$", value):
            raise ValueError(r"must validate the regular expression /^[a-zA-Z0-9_\-\.\/]+$/")
        return value

    @field_validator('s3_bucket')
    def s3_bucket_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[a-z0-9][a-z0-9.\-]*[a-z0-9]$", value):
            raise ValueError(r"must validate the regular expression /^[a-z0-9][a-z0-9.\-]*[a-z0-9]$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreatePdfRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if filename (nullable) is None
        # and model_fields_set contains the field
        if self.filename is None and "filename" in self.model_fields_set:
            _dict['filename'] = None

        # set to None if s3_filepath (nullable) is None
        # and model_fields_set contains the field
        if self.s3_filepath is None and "s3_filepath" in self.model_fields_set:
            _dict['s3_filepath'] = None

        # set to None if s3_bucket (nullable) is None
        # and model_fields_set contains the field
        if self.s3_bucket is None and "s3_bucket" in self.model_fields_set:
            _dict['s3_bucket'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreatePdfRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "template_id": obj.get("template_id"),
            "data": obj.get("data"),
            "export_type": obj.get("export_type"),
            "expiration": obj.get("expiration") if obj.get("expiration") is not None else 86400,
            "filename": obj.get("filename"),
            "store_s3": obj.get("store_s3") if obj.get("store_s3") is not None else False,
            "s3_filepath": obj.get("s3_filepath"),
            "s3_bucket": obj.get("s3_bucket")
        })
        return _obj


