# coding: utf-8

"""
    TemplateFox API

    Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

    The version of the OpenAPI document: 1.13.0
    Contact: support@templatefox.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from templatefox.models.brand_inputs import BrandInputs
from templatefox.models.create_agent_template_request_preset import CreateAgentTemplateRequestPreset
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreateAgentTemplateRequest(BaseModel):
    """
    CreateAgentTemplateRequest
    """ # noqa: E501
    instructions: Annotated[str, Field(min_length=10, strict=True, max_length=4000)] = Field(description="What the template should look like and which layers it needs, in natural language.")
    name: Annotated[str, Field(min_length=1, strict=True, max_length=100)] = Field(description="Template name")
    preset: Optional[CreateAgentTemplateRequestPreset] = None
    width: Optional[Annotated[int, Field(le=8000, strict=True, ge=16)]] = None
    height: Optional[Annotated[int, Field(le=8000, strict=True, ge=16)]] = None
    brand: Optional[BrandInputs] = None
    __properties: ClassVar[List[str]] = ["instructions", "name", "preset", "width", "height", "brand"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateAgentTemplateRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of brand
        if self.brand:
            _dict['brand'] = self.brand.to_dict()
        # set to None if preset (nullable) is None
        # and model_fields_set contains the field
        if self.preset is None and "preset" in self.model_fields_set:
            _dict['preset'] = None

        # set to None if width (nullable) is None
        # and model_fields_set contains the field
        if self.width is None and "width" in self.model_fields_set:
            _dict['width'] = None

        # set to None if height (nullable) is None
        # and model_fields_set contains the field
        if self.height is None and "height" in self.model_fields_set:
            _dict['height'] = None

        # set to None if brand (nullable) is None
        # and model_fields_set contains the field
        if self.brand is None and "brand" in self.model_fields_set:
            _dict['brand'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateAgentTemplateRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "instructions": obj.get("instructions"),
            "name": obj.get("name"),
            "preset": obj.get("preset"),
            "width": obj.get("width"),
            "height": obj.get("height"),
            "brand": BrandInputs.from_dict(obj["brand"]) if obj.get("brand") is not None else None
        })
        return _obj


