# coding: utf-8

"""
    TemplateFox API

    Generate PDFs from HTML templates via API. Design once, generate thousands.

    The version of the OpenAPI document: 1.0.0
    Contact: support@pdftemplateapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ExportType(str, Enum):
    """
    PDF export type options
    """

    """
    allowed enum values
    """
    URL = 'url'
    BINARY = 'binary'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ExportType from a JSON string"""
        return cls(json.loads(json_str))


