# coding: utf-8

"""
    TemplateFox API

    Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

    The version of the OpenAPI document: 1.6.1
    Contact: support@pdftemplateapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from templatefox.models.job_status import JobStatus
from typing import Optional, Set
from typing_extensions import Self

class JobStatusResponse(BaseModel):
    """
    Response for job status query
    """ # noqa: E501
    id: StrictStr = Field(description="Job ID")
    status: JobStatus = Field(description="Current job status")
    template_id: StrictStr = Field(description="Template used for generation")
    export_type: StrictStr = Field(description="Export type (url)")
    filename: Optional[StrictStr] = None
    store_s3: StrictBool = Field(description="Whether S3 storage was requested")
    created_at: StrictStr = Field(description="Job creation timestamp (ISO 8601)")
    updated_at: StrictStr = Field(description="Last update timestamp (ISO 8601)")
    completed_at: Optional[StrictStr] = None
    result_url: Optional[StrictStr] = None
    result_filename: Optional[StrictStr] = None
    result_expires_at: Optional[StrictStr] = None
    result_s3_bucket: Optional[StrictStr] = None
    result_s3_key: Optional[StrictStr] = None
    error_message: Optional[StrictStr] = None
    error_code: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["id", "status", "template_id", "export_type", "filename", "store_s3", "created_at", "updated_at", "completed_at", "result_url", "result_filename", "result_expires_at", "result_s3_bucket", "result_s3_key", "error_message", "error_code"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JobStatusResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if filename (nullable) is None
        # and model_fields_set contains the field
        if self.filename is None and "filename" in self.model_fields_set:
            _dict['filename'] = None

        # set to None if completed_at (nullable) is None
        # and model_fields_set contains the field
        if self.completed_at is None and "completed_at" in self.model_fields_set:
            _dict['completed_at'] = None

        # set to None if result_url (nullable) is None
        # and model_fields_set contains the field
        if self.result_url is None and "result_url" in self.model_fields_set:
            _dict['result_url'] = None

        # set to None if result_filename (nullable) is None
        # and model_fields_set contains the field
        if self.result_filename is None and "result_filename" in self.model_fields_set:
            _dict['result_filename'] = None

        # set to None if result_expires_at (nullable) is None
        # and model_fields_set contains the field
        if self.result_expires_at is None and "result_expires_at" in self.model_fields_set:
            _dict['result_expires_at'] = None

        # set to None if result_s3_bucket (nullable) is None
        # and model_fields_set contains the field
        if self.result_s3_bucket is None and "result_s3_bucket" in self.model_fields_set:
            _dict['result_s3_bucket'] = None

        # set to None if result_s3_key (nullable) is None
        # and model_fields_set contains the field
        if self.result_s3_key is None and "result_s3_key" in self.model_fields_set:
            _dict['result_s3_key'] = None

        # set to None if error_message (nullable) is None
        # and model_fields_set contains the field
        if self.error_message is None and "error_message" in self.model_fields_set:
            _dict['error_message'] = None

        # set to None if error_code (nullable) is None
        # and model_fields_set contains the field
        if self.error_code is None and "error_code" in self.model_fields_set:
            _dict['error_code'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JobStatusResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "status": obj.get("status"),
            "template_id": obj.get("template_id"),
            "export_type": obj.get("export_type"),
            "filename": obj.get("filename"),
            "store_s3": obj.get("store_s3"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "completed_at": obj.get("completed_at"),
            "result_url": obj.get("result_url"),
            "result_filename": obj.get("result_filename"),
            "result_expires_at": obj.get("result_expires_at"),
            "result_s3_bucket": obj.get("result_s3_bucket"),
            "result_s3_key": obj.get("result_s3_key"),
            "error_message": obj.get("error_message"),
            "error_code": obj.get("error_code")
        })
        return _obj


