# coding: utf-8

"""
    TemplateFox API

    Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

    The version of the OpenAPI document: 1.10.0
    Contact: support@templatefox.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from templatefox.models.app_routers_v1_pdf_tools_export_type import AppRoutersV1PdfToolsExportType
from templatefox.models.pdf_input import PdfInput
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MergePdfRequest(BaseModel):
    """
    MergePdfRequest
    """ # noqa: E501
    export_type: Optional[AppRoutersV1PdfToolsExportType] = Field(default=None, description="`url` uploads to CDN and returns URL, `binary` returns raw PDF bytes")
    expiration: Optional[Annotated[int, Field(le=604800, strict=True, ge=60)]] = Field(default=86400, description="URL expiration in seconds. Min 60, max 604800. Only applies to `url` export type.")
    filename: Optional[Annotated[str, Field(strict=True, max_length=100)]] = None
    pdfs: Annotated[List[PdfInput], Field(min_length=2)] = Field(description="Ordered list of PDFs to merge. Each entry has either `pdf_url` or `pdf_base64`. Minimum 2.")
    __properties: ClassVar[List[str]] = ["export_type", "expiration", "filename", "pdfs"]

    @field_validator('filename')
    def filename_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[a-zA-Z0-9_\-\.]+$", value):
            raise ValueError(r"must validate the regular expression /^[a-zA-Z0-9_\-\.]+$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MergePdfRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in pdfs (list)
        _items = []
        if self.pdfs:
            for _item_pdfs in self.pdfs:
                if _item_pdfs:
                    _items.append(_item_pdfs.to_dict())
            _dict['pdfs'] = _items
        # set to None if filename (nullable) is None
        # and model_fields_set contains the field
        if self.filename is None and "filename" in self.model_fields_set:
            _dict['filename'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MergePdfRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "export_type": obj.get("export_type"),
            "expiration": obj.get("expiration") if obj.get("expiration") is not None else 86400,
            "filename": obj.get("filename"),
            "pdfs": [PdfInput.from_dict(_item) for _item in obj["pdfs"]] if obj.get("pdfs") is not None else None
        })
        return _obj


