# coding: utf-8

"""
    TemplateFox API

    Generate PDFs from HTML templates via API. Design once, generate thousands.

    The version of the OpenAPI document: 1.0.0
    Contact: support@pdftemplateapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self

class S3ConfigResponse(BaseModel):
    """
    Response for S3 configuration (with masked secret)
    """ # noqa: E501
    configured: StrictBool = Field(description="Whether S3 is configured")
    endpoint_url: StrictStr = Field(description="S3-compatible endpoint URL")
    access_key_id: StrictStr = Field(description="Access key ID")
    secret_access_key_masked: StrictStr = Field(description="Masked secret access key (shows first 4 and last 4 characters)")
    bucket_name: StrictStr = Field(description="S3 bucket name")
    default_prefix: StrictStr = Field(description="Default path prefix for uploads")
    __properties: ClassVar[List[str]] = ["configured", "endpoint_url", "access_key_id", "secret_access_key_masked", "bucket_name", "default_prefix"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of S3ConfigResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of S3ConfigResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "configured": obj.get("configured"),
            "endpoint_url": obj.get("endpoint_url"),
            "access_key_id": obj.get("access_key_id"),
            "secret_access_key_masked": obj.get("secret_access_key_masked"),
            "bucket_name": obj.get("bucket_name"),
            "default_prefix": obj.get("default_prefix")
        })
        return _obj


