# coding: utf-8

"""
    TemplateFox API

    Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

    The version of the OpenAPI document: 1.4.0
    Contact: support@pdftemplateapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class S3ConfigRequest(BaseModel):
    """
    Request model for S3 configuration
    """ # noqa: E501
    endpoint_url: Annotated[str, Field(min_length=10, strict=True, max_length=200)] = Field(description="S3-compatible endpoint URL. Must start with https://")
    access_key_id: Annotated[str, Field(min_length=16, strict=True, max_length=128)] = Field(description="Access key ID for S3 authentication")
    secret_access_key: Optional[Annotated[str, Field(min_length=16, strict=True, max_length=128)]] = None
    bucket_name: Annotated[str, Field(min_length=3, strict=True, max_length=63)] = Field(description="S3 bucket name. Must follow S3 naming conventions (lowercase, no underscores)")
    default_prefix: Optional[Annotated[str, Field(strict=True, max_length=500)]] = Field(default='', description="Default path prefix for uploaded files. Can include slashes for folder structure")
    __properties: ClassVar[List[str]] = ["endpoint_url", "access_key_id", "secret_access_key", "bucket_name", "default_prefix"]

    @field_validator('endpoint_url')
    def endpoint_url_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^https:\/\/", value):
            raise ValueError(r"must validate the regular expression /^https:\/\//")
        return value

    @field_validator('bucket_name')
    def bucket_name_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[a-z0-9][a-z0-9.\-]*[a-z0-9]$", value):
            raise ValueError(r"must validate the regular expression /^[a-z0-9][a-z0-9.\-]*[a-z0-9]$/")
        return value

    @field_validator('default_prefix')
    def default_prefix_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[a-zA-Z0-9_\-\.\/]*$", value):
            raise ValueError(r"must validate the regular expression /^[a-zA-Z0-9_\-\.\/]*$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of S3ConfigRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if secret_access_key (nullable) is None
        # and model_fields_set contains the field
        if self.secret_access_key is None and "secret_access_key" in self.model_fields_set:
            _dict['secret_access_key'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of S3ConfigRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "endpoint_url": obj.get("endpoint_url"),
            "access_key_id": obj.get("access_key_id"),
            "secret_access_key": obj.get("secret_access_key"),
            "bucket_name": obj.get("bucket_name"),
            "default_prefix": obj.get("default_prefix") if obj.get("default_prefix") is not None else ''
        })
        return _obj


