# coding: utf-8

"""
    TemplateFox API

    Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.

    The version of the OpenAPI document: 1.4.0
    Contact: support@pdftemplateapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from templatefox.models.template_field_spec import TemplateFieldSpec
from typing import Optional, Set
from typing_extensions import Self

class TemplateField(BaseModel):
    """
    Field definition for template variables (compatible with Zapier and Make.com)
    """ # noqa: E501
    key: StrictStr = Field(description="Field key/identifier")
    label: StrictStr = Field(description="Human-readable label")
    type: Optional[StrictStr] = Field(default='string', description="Field type: string, integer, number, boolean, array")
    required: Optional[StrictBool] = Field(default=False, description="Whether the field is required")
    help_text: Optional[StrictStr] = Field(default=None, alias="helpText")
    spec: Optional[List[TemplateFieldSpec]] = None
    __properties: ClassVar[List[str]] = ["key", "label", "type", "required", "helpText", "spec"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TemplateField from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in spec (list)
        _items = []
        if self.spec:
            for _item_spec in self.spec:
                if _item_spec:
                    _items.append(_item_spec.to_dict())
            _dict['spec'] = _items
        # set to None if help_text (nullable) is None
        # and model_fields_set contains the field
        if self.help_text is None and "help_text" in self.model_fields_set:
            _dict['helpText'] = None

        # set to None if spec (nullable) is None
        # and model_fields_set contains the field
        if self.spec is None and "spec" in self.model_fields_set:
            _dict['spec'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TemplateField from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "key": obj.get("key"),
            "label": obj.get("label"),
            "type": obj.get("type") if obj.get("type") is not None else 'string',
            "required": obj.get("required") if obj.get("required") is not None else False,
            "helpText": obj.get("helpText"),
            "spec": [TemplateFieldSpec.from_dict(_item) for _item in obj["spec"]] if obj.get("spec") is not None else None
        })
        return _obj


